repos:
  - repo: local
    hooks:
      - id: generate_pipeline
        name: generate_pipeline
        description: Generates the yaml pipelines for transits and spokes
        entry: python scripts/generate_pipelines.py
        language: system
        always_run: true
        pass_filenames: false

  # - repo: https://github.com/cytopia/docker-terragrunt-fmt.git
  #   rev: "0.4"
  #   hooks:
  #     - id: terragrunt-fmt
  #       name: terragrunt-fmt
  #       entry: make lint
  #       language: docker