repos:
  - repo: local
    hooks:
      - id: generate_pipeline
        name: generate_pipeline
        description: Generates the yaml pipelines for transits and spokes
        entry: python scripts/generate_pipelines.py
        language: system
        always_run: true
        pass_filenames: false


  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.59.0"
    hooks:
      - id: terragrunt_fmt # Ensures terraform formatting is correct
        always_run: true

  # Need to look into this
  # - repo: https://github.com/cytopia/docker-terragrunt-fmt.git
  #   rev: "0.4"
  #   hooks:
  #     - id: terragrunt-fmt
  #       name: terragrunt-fmt
  #       entry: make lint
  #       language: docker