repos:
  - repo: local
    hooks:
      - id: generate_pipeline
        name: generate_pipeline
        entry: python scripts/generate_pipelines.py
        language: system
        always_run: true
        pass_filenames: false