repos:
  - repo: local
    hooks:
      - id: generate_pipeline
        name: generate_pipeline
        description: Generates the yaml pipelines for transits and spokes
        entry: python scripts/generate_pipelines.py
        language: system
        always_run: true
        pass_filenames: false


  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.62.3"
    hooks:
      - id: terragrunt_fmt # Ensures terraform formatting is correct
        always_run: true
