repos:
  - repo: local
    hooks:
      - id: generate_pipeline
        name: generate_pipeline
        description: Generates the yaml pipelines for transits and spokes
        entry: python scripts/generate_pipelines.py
        language: system
        always_run: true
        pass_filenames: false

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.59.0
    hooks:
      - id: terraform_fmt