parameters:
- name: environment
  type: string
- name: serviceConnectionName
  type: string
- name: action
  type: string
  default: plan

stages:
- stage: ControllerDeploymentStage
  displayName: Aviatrix Controller Deployment
  variables:
    - group: ${{ parameters.environment }}-state
    - group: ${{ parameters.environment }}-controller
  jobs:
    - job: ControllerDeploymentJob
      displayName: Aviatrix Controller Deployment
      variables:
        terraform_path: $(System.DefaultWorkingDirectory)/terragrunt/${{ parameters.environment }}/management/controller
        plan_file: controller
        ${{ if eq(parameters.action, 'destroy') }}:
          displayName: "Destroying Controller"
          plan: "terragrunt plan -out=${{ variables.plan_file }} -destroy"
          deploy: "terragrunt apply ${{ variables.plan_file }}"
        ${{ if or(eq(variables['Build.Reason'], 'PullRequest' ), eq(parameters.action, 'plan')) }}:
          displayName: "Planning Controller"
          plan: "terragrunt plan -out=${{ variables.plan_file }}"
          deploy: ""
        ${{ if and(ne(variables['Build.Reason'], 'PullRequest'), eq(parameters.action, 'apply')) }}:
          displayName: "Deploying Controller"
          plan: "terragrunt plan -out=${{ variables.plan_file }}"
          deploy: "terragrunt apply ${{ variables.plan_file }}"

      steps:
        - template: ../common.yml
          parameters:
            serviceConnectionName: ${{ parameters.serviceConnectionName }}

        - script: |
            cd $(terraform_path)
            terragrunt init
            ${{ variables.plan }}
            ${{ variables.deploy }}
          displayName: ${{ variables.displayName }}
          env:
            REMOTE_STATE_RESOURCE_GROUP: $(stateResourceGroupName)
            REMOTE_STATE_STORAGE_ACCOUNT: $(stateStorageAccountName)
            USER_PUBLIC_IP_ADDRESS: $(userPublicIpAddress)
            BUILD_AGENT_PUBLIC_IP_ADDRESS: $(buildAgentPublicIpAddress)
            AZURE_ACCESS_ACCOUNT: $(aviatrixAzureAccessAcountName)
            AVIATRIX_CONTROLLER_USERNAME: $(aviatrixControllerUsername)
            CONTROLLER_CUSTOMER_ID: $(aviatrixCustomerId)
            ADMIN_EMAIL: $(adminEmail)
            ARM_CLIENT_ID: $(SERVICE_PRINCIPAL_ID)
            ARM_SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
            ARM_TENANT_ID: $(TENANT_ID)
            ARM_CLIENT_SECRET: $(SERVICE_PRINCIPAL_KEY)