stages:
- stage: InitialDeploymentStage
  displayName: Initial Deployment
  variables:
    - group: aviatrix-initial-setup
  jobs:
    - job: InitialDeploymentJob
      displayName: Initial Deployment
      steps:
        - template: templates/common.yml
          parameters:
            serviceConnectionName: TRAVIS_CONNECTION

        - task: AzureCLI@2
          displayName: Create Resource Group, Storage Account and Container
          inputs:
            azureSubscription: TRAVIS_CONNECTION
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              az group create --location $(location) --name $(resourceGroupName)
              az storage account create \
                --name $(storageAccountName) \
                --resource-group $(resourceGroupName) \
                --https-only true \
                --location $(location) \
                --sku Standard_GRS \
                --kind StorageV2 \
                --allow-blob-public-access false \
                --allow-shared-key-access false \
                --min-tls-version TLS1_2
              az role assignment create \
                --role "Storage Blob Data Owner" \
                --scope "/subscriptions/$(SUBSCRIPTION_ID)/resourceGroups/$(resourceGroupName)/providers/Microsoft.Storage/storageAccounts/$(storageAccountName)" \
                --assignee-principal-type ServicePrincipal \
                --assignee-object-id $(SERVICE_PRINCIPAL_OBJECT_ID) \
                --subscription $(SUBSCRIPTION_ID)
              az storage container create \
                --name $(storageContainerName) \
                --account-name $(storageAccountName) \
                --auth-mode login \
                --public-access off
            addSpnToEnvironment: true

        - script: |
            terraform chdir=terraform/setup init \
              -backend-config="storage_account_name=$(storageAccountName)" \
              -backend-config="container_name=$(storageContainerName)" \
              -backend-config="subscription_id=$(SUBSCRIPTION_ID)" \
              -backend-config="tenant_id=$(TENANT_ID)"
            terraform chdir=terraform/setup plan -out=initial_config \
              -var 'user_principal_id=$(userPrincipalId)' \
              -var 'aviatrix_customer_id=$(aviatrixCustomerId)' \
              -var 'azure_subscription_id=$(SUBSCRIPTION_ID)' \
              -var 'azure_tenant_id=$(TENANT_ID)' \
              -var 'azure_application_id=$(SERVICE_PRINCIPAL_ID)' \
              -var 'azure_application_key=$(SERVICE_PRINCIPAL_KEY)' \
              -var 'aws_access_key=$(awsAccessKey)' \
              -var 'aws_secret_key=$(awsSecretKey)' \
              -var 'aws_account_number=$(awsAccountNumber)' \
              -var 'gcp_project_id=$(gcpProjectId)' \
              -var 'gcp_secret_json=$(gcpSecretJson)'
            terraform apply initial_config
          displayName: Perform Terraform Operations
          env:
            ARM_CLIENT_ID: $(SERVICE_PRINCIPAL_ID)
            ARM_SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
            ARM_TENANT_ID: $(TENANT_ID)
            ARM_CLIENT_SECRET: $(SERVICE_PRINCIPAL_KEY)
