parameters:
- name: destroy
  type: boolean
  default: false
- name: spokes
  type: object
- name: environment
  type: string
- name: serviceConnectionName
  type: string

stages:
- ${{ each region in parameters.spokes }}:
  - ${{ each spoke in region.spokes }}:
    - stage: ${{ replace(region.region, '-', '_') }}${{ spoke }}SpokeDeploymentStage
      dependsOn:
       - "${{ replace(region.region, '-', '_') }}${{ region.csp }}TransitsDeploymentStage"
      displayName: Azure ${{ region.region }} ${{ spoke }} Deployment
      variables:
        - group: ${{ parameters.environment }}-state
      jobs:
        - job: ${{ spoke }}SpokesDeploymentJob
          displayName: Deploy Spoke ${{ spoke }}
          variables:
            terraform_path: $(System.DefaultWorkingDirectory)/terraform/${{ parameters.environment }}/${{ region.csp }}/${{ region.region }}/spokes/${{ spoke }}
            plan_file: spokes
            ${{ if parameters.destroy }}:
              displayName: "Destroying Spoke"
              plan: "terragrunt plan -out=${{ variables.plan_file }} -destroy"
              deploy: "terragrunt apply ${{ variables.plan_file }}"
            ${{ if or(eq(variables['Build.Reason'], 'PullRequest' ), parameters.plan) }}:
              displayName: "Planning Spoke"
              plan: "terragrunt plan -out=${{ variables.plan_file }}"
              deploy: ""
            ${{ if and(ne(variables['Build.Reason'], 'PullRequest'), not(parameters.plan), not(parameters.destroy)) }}:
              displayName: "Deploying Spoke"
              plan: "terragrunt plan -out=${{ variables.plan_file }}"
              deploy: "terragrunt apply ${{ variables.plan_file }}"

          steps:
            - template: ../common.yml
              parameters:
                serviceConnectionName: ${{ parameters.serviceConnectionName }}

            - script: |
                cd $(terraform_path)
                terragrunt init
                ${{ variables.plan }}
                ${{ variables.deploy }}
              displayName: ${{ variables.displayName }}
              env:
                REMOTE_STATE_RESOURCE_GROUP: $(stateResourceGroupName)
                REMOTE_STATE_STORAGE_ACCOUNT: $(stateStorageAccountName)
                ARM_CLIENT_ID: $(SERVICE_PRINCIPAL_ID)
                ARM_SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
                ARM_TENANT_ID: $(TENANT_ID)
                ARM_CLIENT_SECRET: $(SERVICE_PRINCIPAL_KEY)