parameters:
- name: azureRegions
  type: object
- name: environment
  type: string
- name: serviceConnectionName
  type: string

stages:
- ${{ each region in parameters.azureRegions }}:
  - stage: ${{ replace(region, '-', '_') }}TransitsDeploymentStage
    displayName: Azure Hub ${{ region }} Deployment
    variables:
      - group: aviatrix-variables
    jobs:
      - job: ${{ replace(region, '-', '_') }}TransitDeploymentJob
        displayName: Azure Hub ${{ region }} Deployment
        variables:
          terraform_path: $(System.DefaultWorkingDirectory)/terraform/${{ parameters.environment }}/azure/${{ region }}/hub
          plan_file: azure_hub
          ${{ if eq(variables['Build.Reason'], 'PullRequest' ) }}:
            plan: "terragrunt plan -out=${{ variables.plan_file }}"
            deploy: ""
          ${{ if ne(variables['Build.Reason'], 'PullRequest' ) }}:
            plan: "terragrunt plan -out=${{ variables.plan_file }}"
            deploy: "terraform -chdir=${{ variables.terraform_path }} apply ${{ variables.plan_file }}"
        steps:
          - template: ../common.yml
            parameters:
              serviceConnectionName: ${{ parameters.serviceConnectionName }}

          - task: AzureKeyVault@2
            inputs:
              azureSubscription: ${{ parameters.serviceConnectionName }}
              KeyVaultName: ${{ replace(variables.resourceGroupName, '-rg', '-kv') }}
              SecretsFilter: $(aviatrixControllerSecretName)

          - script: |
              cd $(terraform_path)
              terragrunt init
              ${{ variables.plan }}
              ${{ variables.deploy }}
            displayName: Deploy Azure Transits via Terraform
            env:
              REMOTE_STATE_RESOURCE_GROUP: $(resourceGroupName)
              REMOTE_STATE_STORAGE_ACCOUNT: $(traviscontrolsa)
              AVIATRIX_CONTROLLER_USERNAME: $(aviatrixControllerUsername)
              AVIATRIX_CONTROLLER_IP: $(aviatrixControllerIp)
              AVIATRIX_CONTROLLER_PASSWORD: $($(aviatrixControllerSecretName))
              AVIATRIX_ACCESS_ACCOUNT: $(aviatrixAzureAccessAcountName)
              KEY_VAULT_ID: $(azureKeyVaultId)
              USER_PUBLIC_IP: $(userPublicIpAddress)
              ARM_CLIENT_ID: $(SERVICE_PRINCIPAL_ID)
              ARM_SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(TENANT_ID)
              ARM_CLIENT_SECRET: $(SERVICE_PRINCIPAL_KEY)