trigger: none
pool: ubuntu20-latest

variables:
  environment: dev

stages:
  - template: templates/stages/initial.setup.yml
    parameters:
      environment: ${{ variables.environment }}
  - template: templates/stages/aviatrix.controller.yml
  - template: templates/stages/transits.yml
    parameters:
      serviceConnectionName: TRAVIS_CONNECTION
      environment: ${{ variables.environment }}
      azureRegions:
        - east-us-1
        - south-central-us