trigger: none
pool: ubuntu20-latest

parameters:
- name: destroy
  displayName: Run Terraform Destroy?
  type: boolean
  default: false
- name: plan
  displayName: Run Terraform Plan
  type: boolean
  default: false

variables:
  environment: dev
  serviceConnectionName: TRAVIS_CONNECTION

stages:
- template: templates/stages/state.setup.yml
  parameters:
    environment: ${{ variables.environment }}
    serviceConnectionName: ${{ variables.serviceConnectionName }}

- template: templates/stages/aviatrix.controller.yml
  parameters:
    plan: ${{ parameters.plan }}
    destroy: ${{ parameters.destroy }}
    serviceConnectionName: ${{ variables.serviceConnectionName }}
    environment: ${{ variables.environment }}

- template: templates/stages/transits.yml
  parameters:
    plan: ${{ parameters.plan }}
    destroy: ${{ parameters.destroy }}
    serviceConnectionName: ${{ variables.serviceConnectionName }}
    environment: ${{ variables.environment }}
    transits:
    - csp: azure
      region: east-us-1
    - csp: azure
      region: south-central-us

- template: templates/stages/spokes.yml
  parameters:
    destroy: ${{ parameters.destroy }}
    serviceConnectionName: ${{ variables.serviceConnectionName }}
    environment: ${{ variables.environment }}
    spokes:
    - csp: azure
      region: east-us-1
      spokes:
      - spoke1
    - csp: azure
      region: south-central-us
      spokes:
      - spoke1
